main: mb.Guayando.MineBank
name: MineBank
version: 1.0.3
author: Guayando
api-version: 1.13
depend: [Vault]
description: Un plugin que añade un banco de dinero.

commands:
  minebank:
    description: Comando principal
    usage: /minebank <arg0>
    aliases: mb
  bank:
    description: Comando del banco
    usage: /bank <arg0> [<arg1> <arg2> ...]

permissions:
  minebank.*:
    default: op
    description: Todos los permisos
  minebank.reload:
    description: Sirve para recargar el plugin
  minebank.help:
    description: Sirve para ver lista de comandos de minebank
  minebank.version:
    description: Sirve para ver la version del plugin
  minebank.plugin:
    description: Sirve para ver el link de descarga del plugin
  minebank.permissions:
    description: Sirve para ver los permisos del plugin
  minebank.updatechecker:
    description: Sirve para comprobar si hay una nueva version del plugin
  minebank.use:
    description: Sirve para poder usar el plugin
  minebank.admin:
    description: Sirve para poder usar /bank set y otros comandos de administrador
  minebank.helpbank:
    description: Sirve para ver lista de comandos de bank